apiVersion: apps/v1
kind: Deployment
metadata:
  name: itops-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itops-vote-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: itops-vote-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: itops-vote-front
        image: dvaitopsdemo1acr.azurecr.io/aci-helloitops:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
