on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: dvaitopsdemo1acr.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -t dvaitopsdemo1acr.azurecr.io/aci-helloitops:${{ github.sha }} .
            docker push dvaitopsdemo1acr.azurecr.io/aci-helloitops:${{ github.sha }}

        - name: 'Deploy to Azure Web Apps for Containers'
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'webapp-container-helloitops'
            images: 'dvaitopsdemo1acr.azurecr.io/aci-helloitops:${{ github.sha }}'
